name: Build and push image to ACR

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ demo123456.azurecr.io }}
        username: ${{ demo123456.azurecr.io }}
        password: ${{ zQVjOZStl3cuC7FxGlnlmJtEJfbQxic2EAGXED+kKH+ACRCqP9Ra }}

    - name: Build and push image
      run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/firstcontainerappacracr:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/firstcontainerappacracr:${{ github.sha }}
